key: group_content_builder
title: Content Builder
location:
  -
    - { param: "post_type", operator: "==", value: "page" }
menu_order: 0
position: "acf_after_title"
style: "default"
label_placement: "top"
instruction_placement: "label"
hide_on_screen: ""
active: 1
description:
fields: 
    -
        key: "field_builder"
        label: "Content Builder"
        name: "content_builder"
        type: "flexible_content"
        instructions: 
        required: 0
        wrapper: { width: "", class: "", id: "" }
        button_label: "Add Row"
        layouts: 
            -
                key: layout_highlights
                name: highlights
                label: Highlights
                instructions: "will auto populate based on information in the theme settings"
                display: block
                sub_fields:
            -
                key: layout_basic
                name: basic_content
                label: Basic Content
                instructions: "Basic content on a whate background"
                display: block
                sub_fields:
                    -
                        key: field_drop_caps_letter
                        label: Drop Caps Letter
                        name: drop_caps_letter
                        type: text
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                    -
                        key: field_drop_caps_content
                        label: Drop Caps Content
                        name: drop_caps_content
                        type: textarea
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                    -
                        key: field_basic_content
                        label: Content
                        name: content
                        type: wysiwyg
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                        tabs: all
                        toolbar: full
                        media_upload: 1
            -
                key: layout_popular
                name: popular
                label: Popular Products
                display: block
                sub_fields:
                    -
                        key: 'field_5818e054f1b07'
                        label: 'Products'
                        name: 'products'
                        type: 'post_object'
                        instructions: ''
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: '', class: '', id: '' }
                        post_type: ['product']
                        allow_null: 0
                        multiple: 1
                        return_format: 'object'
                        ui: 1
