key: "group_header"
title: "Header"
location:
  -
    - { param: "post_type", operator: "==", value: "post" }
  -
    - { param: "post_type", operator: "==", value: "page" }
menu_order: 0
position: "normal"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "field_heading"
    label:  "Heading"
    name:  "header_heading"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "33", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_heading_background"
    label:  "Background"
    name:  "header_background"
    type:  "file"
    return_format: "array"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "33", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_heading_share"
    label:  "Include Share Buttons"
    name:  "header_share"
    type:  "true_false"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "34", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_heading_content"
    label:  "Content"
    name:  "header_content"
    type:  "wysiwyg"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0