key: group_product_builder
title: Product Content Builder
location:
  -
    - { param: "post_type", operator: "==", value: "product" }
menu_order: 0
position: "acf_after_title"
style: "default"
label_placement: "top"
instruction_placement: "label"
hide_on_screen: ""
active: 1
description:
fields:
  -
    key:  "field_small_heading"
    label:  "Small Heading"
    name:  "small_heading"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_inside_repeater"
    label:  "Whats Inside"
    name:  "inside"
    type: repeater
    instructions:
    required: 0
    conditional_logic: 0
    wrapper: { width: "", class: "", id: "" }
    collapsed:
    min: 0
    max: 0
    layout: block
    button_label: Add Row
    sub_fields:
      -
        key:  "field_inside_title"
        label:  "Text"
        name:  "text"
        type:  "text"
        instructions:  ""
        required:  1,
        conditional_logic:  0,
        wrapper:  { width:  "50", class:  "", id:  "" }
        default_value:  ""
        placeholder:  ""
        prepend:  ""
        append:  ""
        maxlength:  ""
        readonly:  0
        disabled:  0
      -
        key:  "field_inside_link"
        label:  "URL"
        name:  "url"
        type:  "url"
        instructions:  ""
        required:  0,
        conditional_logic:  0,
        wrapper:  { width:  "50", class:  "", id:  "" }
        default_value:  ""
        placeholder:  ""
        prepend:  ""
        append:  ""
        maxlength:  ""
        readonly:  0
        disabled:  0