key: group_product_builder
title: Product Content Builder
location:
  -
    - { param: "post_type", operator: "==", value: "product" }
menu_order: 0
position: "acf_after_title"
style: "default"
label_placement: "top"
instruction_placement: "label"
hide_on_screen: ""
active: 1
description:
fields:
  -
    key:  "field_tagline"
    label:  "Small Heading"
    name:  "small_heading"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_inside_repeater"
    label:  "Whats Inside"
    name:  "inside"
    type: repeater
    instructions:
    required: 0
    conditional_logic: 0
    wrapper: { width: "", class: "", id: "" }
    collapsed:
    min: 0
    max: 0
    layout: block
    button_label: Add Row
    sub_fields:
      -
        key:  "field_inside_title"
        label:  "Text"
        name:  "text"
        type:  "text"
        instructions:  ""
        required:  1,
        conditional_logic:  0,
        wrapper:  { width:  "50", class:  "", id:  "" }
        default_value:  ""
        placeholder:  ""
        prepend:  ""
        append:  ""
        maxlength:  ""
        readonly:  0
        disabled:  0
      -
        key:  "field_inside_link"
        label:  "URL"
        name:  "url"
        type:  "url"
        instructions:  ""
        required:  1,
        conditional_logic:  0,
        wrapper:  { width:  "50", class:  "", id:  "" }
        default_value:  ""
        placeholder:  ""
        prepend:  ""
        append:  ""
        maxlength:  ""
        readonly:  0
        disabled:  0
  -
    key: field_promotion_highlights
    label: 100% Satisfaction
    name: highlights
    type: repeater
    instructions:
    required: 1
    conditional_logic: 0
    wrapper: { width: "", class: "", id: "" }
    collapsed:
    min: 4
    max: 4
    layout: block
    button_label: Add Row
    sub_fields:
        -
            key: field_promotion_image
            label: Image
            name: image
            type: image
            instructions:
            required: 0
            conditional_logic: 0
            wrapper: { width: 50, class: "", id: "" }
            return_format: array
            preview_size: thumbnail
            library: all
            min_width:
            min_height:
            min_size:
            max_width:
            max_height:
            max_size:
            mime_types:
        -
            key: field_promotion_heading
            label: Heading
            name: heading
            type: text
            instructions:
            required: 1
            conditional_logic: 0
            wrapper: { width: 50, class: "", id: "" }
            default_value:
            placeholder:
            prepend:
            append:
            maxlength:
        -
            key: field_promotion_content
            label: Content
            name: content
            type: wysiwyg
            instructions:
            required: 1
            conditional_logic: 0
            wrapper: { width: "", class: "", id: "" }
            default_value:
            tabs: all
            toolbar: basic
            media_upload: 0