key: "group_theme_options"
title: "Theme Options"
location:
  -
    - { param: "options_page", operator: "==", value: "acf-options-theme-options" }
menu_order: 0
position: "normal"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "field_57d9b0cfe4c9f"
    label:  "Google Analytics ID"
    name:  "google_analytics_id"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_57d9c7b4d5985"
    label:  "Logo"
    name:  "logo"
    type:  "image"
    instructions:  ""
    required:  1
    conditional_logic:  0
    wrapper:  {width:  50, class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_57d9c7f3a6160"
    label:  "Favicon"
    name:  "favicon"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  50, class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_default_heading_background"
    label:  "Default Heading Background"
    name:  "header_background"
    type:  "image"
    instructions:  ""
    required:  1,
    conditional_logic:  0,
    wrapper:  { width:  50, class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_shop_background"
    label:  "Shop Background"
    name:  "Shop_background"
    type:  "image"
    instructions:  ""
    required:  1,
    conditional_logic:  0,
    wrapper:  { width:  50, class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key: field_highlights_heading
    label: Heading Below Box
    name: highlights_heading
    type: text
    instructions:
    required: 1
    conditional_logic: 0
    wrapper: { width: 50, class: "", id: "" }
    default_value:
    placeholder:
    prepend:
    append:
    maxlength:
  -
    key: field_highlights_box
    label: Box Image
    name: highlights_box
    type: image
    instructions:
    required: 1
    conditional_logic: 0
    wrapper: { width: 50, class: "", id: "" }
    return_format: array
    preview_size: thumbnail
    library: all
    min_width:
    min_height:
    min_size:
    max_width:
    max_height:
    max_size:
    mime_types:
  -
    key: field_promotion_highlights
    label: Highlights
    name: highlights
    type: repeater
    instructions:
    required: 1
    conditional_logic: 0
    wrapper: { width: "", class: "", id: "" }
    collapsed:
    min: 4
    max: 4
    layout: block
    button_label: Add Row
    sub_fields:
        -
            key: field_promotion_image
            label: Image
            name: image
            type: image
            instructions:
            required: 0
            conditional_logic: 0
            wrapper: { width: 50, class: "", id: "" }
            return_format: array
            preview_size: thumbnail
            library: all
            min_width:
            min_height:
            min_size:
            max_width:
            max_height:
            max_size:
            mime_types:
        -
            key: field_promotion_heading
            label: Heading
            name: heading
            type: text
            instructions:
            required: 1
            conditional_logic: 0
            wrapper: { width: 50, class: "", id: "" }
            default_value:
            placeholder:
            prepend:
            append:
            maxlength:
        -
            key: field_promotion_content
            label: Content
            name: content
            type: wysiwyg
            instructions:
            required: 1
            conditional_logic: 0
            wrapper: { width: "", class: "", id: "" }
            default_value:
            tabs: all
            toolbar: basic
            media_upload: 0
  -
    key:  "field_copyright"
    label:  "Copyright"
    name:  "copyright"
    type:  "wysiwyg"
    toolbar: "basic"
    media_upload: 0
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "", class:  "", id:  "" }
  -
    key:  "field_youtube"
    label:  "Youtube"
    name:  "youtube"
    type:  "url"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
  -
    key:  "field_facebook"
    label:  "Facebook"
    name:  "facebook"
    type:  "url"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
  -
    key:  "field_instagram"
    label:  "Instagram"
    name:  "instagram"
    type:  "url"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
  -
    key:  "field_pinterest"
    label:  "Pinterest"
    name:  "pinterest"
    type:  "url"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
